# -*- coding: utf-8 -*-
"""
Created on Mon Oct 26 11:36:55 2020

@author: asha_
"""
import tkinter
rootE=tkinter.Tk()
rootE.title("Employee registration")
rootE.geometry('400x400')
rootE.config(bg="#8080ff")
rootE.iconbitmap("logo1.ico")
var = tkinter.StringVar(master=rootE)
import mysql.connector as s
c=s.connect(host='127.0.0.1',database='hospital',user='root',password='mayk2002',auth_plugin='mysql_native_password')
H=tkinter.Label(rootE,text="EMPLOYEE REGISTRATION",font="Arial 13 bold",bg="#8080ff",fg="darkblue")
H.place(x=50,y=20)
def delo():
    global u,d1,rootDE
    rootDE=tkinter.Tk()
    rootDE.geometry("250x250")
    rootDE.title("EMPLOYEE DELETION")
    rootDE.config(bg="#8080ff")
    h1=tkinter.Label(rootDE,text="ENTER EMPLOYEE ID TO DELETE :",bg="#8080ff",fg="darkblue")
    h1.place(x=20,y=10)
    d1=tkinter.Entry(rootDE)
    d1.place(x=20,y=40)
    u=t1.get()
    B1=tkinter.Button(rootDE,text="DELETE",command=lambda:delling(),bg="#8080ff",fg="darkblue")
    B1.place(x=20,y=70)
    rootDE.mainloop()
def lo():
    global t2,r1,lb,t6,t5,t7
    cur=c.cursor()
    u=t1.get()
    t=(u,t2.get(),r1.get(),lb.get(),d[a],t6.get(),t5.get(),t7.get())
    print(t)
    cur.execute("insert into emp values(%s,%s,%s,%s,%s,%s,%s,%s);",t)
    c.commit()
    cur.close()
    cur=c.cursor()
    print("insert into userpass values(",u,",'e1234',)")
    cur.execute("insert into userpass values(%s,'e1234','N')",(u,))
    c.commit()
    cur.close()
    tkinter.Label(rootE,text="This person is an employee now.....",bg="#8080ff",fg="darkblue").place(y=360)
def delling():
    cur=c.cursor()
    t=(d1.get(),)
    print(t)
    cur.execute("select * from emp where E_id=%s;",t)
    a=cur.fetchall()
    c.commit()
    cur.close()
    if a!=[]:
        cur=c.cursor()
        t=(d1.get(),)
        print(t)
        cur.execute("delete from emp where E_id=%s;",t)
        c.commit()
        cur.close()
        cur=c.cursor()
        t=(d1.get(),)
        print(t)
        cur.execute("delete from userpass where E_id=%s;",t)
        c.commit()
        cur.close()
        as12=tkinter.Label(rootDE,text="The person with this id is not an employee now.....",bg="#8080ff",fg="darkblue")
        as12.place(y=50)
        rootDE.after(3000,lambda:as12.place_forget())
    else:
        as1=tkinter.Label(rootDE,text="The person not an employee(id not found).....",bg="#8080ff",fg="darkblue")
        as1.place(y=100)
        rootDE.after(3000,lambda:as1.place_forget())
d={"doctor":200000,"nurse":50000,"receptionist":30000,"wardboy":10000,"servicestaff":10000,"pathologist":20000,"technisionas":15000}
l1=tkinter.Label(rootE,text="EMPLOYEE ID",bg="#8080ff",fg="darkblue")
l1.place(x=50,y=50)
t1=tkinter.Entry(rootE)
t1.place(x=170,y=50)
l2 = tkinter.Label(rootE, text="EMPLOYEE NAME",bg="#8080ff",fg="darkblue")
l2.place(x=50,y=80)
t2 = tkinter.Entry(rootE)
t2.place(x=170, y=80)
l3 = tkinter.Label(rootE, text="SEX",bg="#8080ff",fg="darkblue")
l3.place(x=50,y=110)
v=tkinter.StringVar()
r1 = tkinter.Entry(rootE)
r1.place(x=170, y=110)
l4 = tkinter.Label(rootE, text="AGE",bg="#8080ff",fg="darkblue")
l4.place(x=50,y=140)
t3=tkinter.Entry(rootE)
t3.place(x=170,y=140)
l5 = tkinter.Label(rootE, text="EMPLOYEE TYPE",bg="#8080ff",fg="darkblue")
l5.place(x=50,y=170)
lb = tkinter.Entry(rootE)
lb.place(x=170, y=170)
l6=tkinter.Label(rootE,text="SALARY",bg="#8080ff",fg="darkblue")
l6.place(x=50,y=200)
x1=tkinter.Button(rootE,text="GET",command=lambda:get(),bg="#8080ff",fg="darkblue")
x1.place(x=260,y=200)
def get():
    global a
    a=lb.get()
    t4=tkinter.Label(rootE,text=d[a],bg="#8080ff",fg="darkblue")
    t4.place(x=170,y=200)
l7 = tkinter.Label(rootE, text="EXPERIENCE",bg="#8080ff",fg="darkblue")
l7.place(x=50,y=230)
t5 = tkinter.Entry(rootE)
t5.place(x=170,y=230)
l8 = tkinter.Label(rootE, text="MOBILE NO",bg="#8080ff",fg="darkblue")
l8.place(x=50,y=260)
t6 = tkinter.Entry(rootE)
t6.place(x=170,y=260)
l9 = tkinter.Label(rootE, text="EMAIL",bg="#8080ff",fg="darkblue")
l9.place(x=50,y=290)
t7=tkinter.Entry(rootE)
t7.place(x=170,y=290)
b1=tkinter.Button(rootE,text="SUBMIT",command=lambda:lo(),bg="#8080ff",fg="darkblue")
b1.place(x=60,y=320)
b2=tkinter.Button(rootE,text="DELETE EMPLOYEE",command=lambda:delo(),bg="#8080ff",fg="darkblue")
b2.place(x=130,y=320)
b3=tkinter.Button(rootE,text="EXIT",command=lambda:rootE.destroy(),bg="#8080ff",fg="darkblue")
b3.place(x=260,y=320)
rootE.mainloop()
